const HARDEN_MESSAGES=Object.freeze({ar:{offline:"أنت غير متصل بالإنترنت. بياناتك باقية في الصفحة؛ حاول الإرسال بعد عودة الاتصال.",online:"عاد الاتصال بالإنترنت."},en:{offline:"You are offline. Your entered data is still here; submit again when the connection returns.",online:"Internet connection restored."},fr:{offline:"Vous êtes hors ligne. Vos données saisies sont conservées ; réessayez lorsque la connexion revient.",online:"Connexion Internet rétablie."},ru:{offline:"Нет подключения к Интернету. Введённые данные сохранены на странице; отправьте снова после восстановления связи.",online:"Подключение к Интернету восстановлено."},uz:{offline:"Internet aloqasi yo‘q. Kiritgan ma’lumotlaringiz sahifada saqlanadi; aloqa qaytgach yana yuboring.",online:"Internet aloqasi tiklandi."}});
function currentMessages(){const lang=String(document.documentElement.lang||document.body?.dataset?.locale||"en").toLowerCase().split("-")[0];return HARDEN_MESSAGES[lang]||HARDEN_MESSAGES.en}
function ensureNetworkStatus(){let box=document.getElementById("basair-network-status");if(box)return box;box=document.createElement("div");box.id="basair-network-status";box.className="basair-network-status";box.setAttribute("role","status");box.setAttribute("aria-live","polite");box.setAttribute("aria-atomic","true");box.hidden=true;document.body.appendChild(box);return box}
let onlineHideTimer=0;function announceNetworkState(isOnline,initial=false){const box=ensureNetworkStatus();clearTimeout(onlineHideTimer);if(isOnline&&initial){box.hidden=true;return}const m=currentMessages();box.textContent=isOnline?m.online:m.offline;box.dataset.state=isOnline?"online":"offline";box.hidden=false;if(isOnline)onlineHideTimer=setTimeout(()=>{box.hidden=true},3200)}
addEventListener("offline",()=>announceNetworkState(false));addEventListener("online",()=>announceNetworkState(true));if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>announceNetworkState(navigator.onLine!==false,true),{once:true});else announceNetworkState(navigator.onLine!==false,true);
document.addEventListener("invalid",e=>{const f=e.target;if(f instanceof HTMLInputElement||f instanceof HTMLTextAreaElement||f instanceof HTMLSelectElement)f.setAttribute("aria-invalid","true")},true);
document.addEventListener("input",e=>{const f=e.target;if((f instanceof HTMLInputElement||f instanceof HTMLTextAreaElement||f instanceof HTMLSelectElement)&&f.getAttribute("aria-invalid")==="true"&&f.checkValidity())f.removeAttribute("aria-invalid")},true);
export function focusInvalidField(form,fieldOrName){if(!form)return;let f=fieldOrName;if(typeof fieldOrName==="string")f=form.elements.namedItem(fieldOrName);if(!(f instanceof HTMLElement))return;f.setAttribute("aria-invalid","true");f.focus({preventScroll:true});f.scrollIntoView({behavior:matchMedia?.("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"center"})}
export function safeStorage(storage,operation,key,value){try{if(!storage)return null;if(operation==="get")return storage.getItem(key);if(operation==="set"){storage.setItem(key,value);return value}if(operation==="remove"){storage.removeItem(key);return null}}catch{}return null}
export function createSubmissionToken(scope,fingerprint){const storageKey=`basair_pending_${scope}`;let pending=null;try{pending=JSON.parse(safeStorage(sessionStorage,"get",storageKey)||"null")}catch{}const now=Date.now();if(pending&&pending.id&&pending.fingerprint===fingerprint&&now-Number(pending.createdAt||0)<1800000)return{id:String(pending.id),storageKey,reused:true};const id=globalThis.crypto&&typeof crypto.randomUUID==="function"?crypto.randomUUID():`${now.toString(36)}-${Math.random().toString(36).slice(2,14)}`;safeStorage(sessionStorage,"set",storageKey,JSON.stringify({id,fingerprint,createdAt:now}));return{id,storageKey,reused:false}}
export function clearSubmissionToken(storageKey){safeStorage(sessionStorage,"remove",storageKey)}
export function sanitizeAttributionMap(value){const src=value&&typeof value==="object"&&!Array.isArray(value)?value:{};const limits={utm_source:200,utm_medium:200,utm_campaign:200,utm_content:200,utm_term:200,gclid:200,fbclid:200,ttclid:200,landingPath:240,landing_path:240,referrer:500,capturedAt:64,captured_at:64};const out={};for(const [k,max] of Object.entries(limits))if(typeof src[k]==="string")out[k]=src[k].trim().slice(0,max);return out}
